version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"     # OTLP gRPC
      - "13133:13133"   # Health
      - "8888:8888"     # Prometheus metrics
      - "8889:8889"     # Internal metrics
    networks:
      - petclinic-net
    depends_on:
      - jaeger
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - petclinic-net

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "9411:9411"
    networks:
      - petclinic-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - petclinic-net

networks:
  petclinic-net:
    name: petclinic-net
    driver: bridge
