version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: petclinic-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - petclinic-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  petclinic:
    build:
      context: ./app
    container_name: petclinic-app
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      spring.datasource.url: jdbc:mysql://mysql:3306/petclinic
      spring.datasource.username: user
      spring.datasource.password: password
      JAVA_TOOL_OPTIONS: "-javaagent:/opt/opentelemetry-javaagent.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    ports:
      - "8080:8080"
      - "9464:9464"
    networks:
      - petclinic-net

volumes:
  mysql_data:

networks:
  petclinic-net:
    name: petclinic-net
    driver: bridge
