name: Build and Test PetClinic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permisos a mvnw
        run: chmod +x ./app/mvnw

      - name: Compilar y testear con Maven
        working-directory: ./app
        run: ./mvnw clean verify

      - name: Construir imagen Docker
        run: docker build -t petclinic-app ./app
