name: Build, Scan and Push PetClinic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permisos a mvnw
        run: chmod +x ./app/mvnw

      - name: Compilar y testear con Maven
        working-directory: ./app
        run: ./mvnw clean verify

      - name: Construir imagen Docker
        run: docker build -t petclinic-app ./app

      - name: Escaneo de seguridad con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: petclinic-app
          format: table
          severity: CRITICAL,HIGH

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Etiquetar imagen Docker
        run: docker tag petclinic-app ${{ secrets.DOCKER_USERNAME }}/petclinic:latest

      - name: Subir imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/petclinic:latest
